#NAME: Jinbean Park
#EMAIL: keiserssose@gmail.com
#ID: 805330751

FILES=lab3a.c README Makefile ext2_fs.h

default:
	gcc -g -Wall -Wextra lab3a.c -o lab3a

dist:
	tar -zcvf lab3a-805330751.tar.gz $(FILES)

clean:
	rm -f lab3a lab3a-805330751.tar.gz