#NAME: Jinbean Park
#EMAIL: keiserssose@gmail.com
#ID: 805330751

FILES=lab1a.c README Makefile

default:
	gcc -g -Wall -Wextra lab1a.c -o lab1a

clean:
	rm -f lab1a lab1a-805330751.tar.gz

dist:
	tar -zcvf lab1a-805330751.tar.gz $(FILES)