#NAME: Jinbean Park
#EMAIL: keiserssose@gmail.com
#ID: 805330751

FILES=lab3b.py README Makefile JB_lab3b

default: 
	rm -f lab3b
	ln JB_lab3b lab3b
	chmod 777 lab3b

clean:
	rm -f lab3b-805330751.tar.gz lab3b

dist:
	tar -zcvf lab3b-805330751.tar.gz $(FILES)